### ISSUE TITLE
Fix Boundary Problems

### ISSUE THREAD

**Issue by maxschommer** [Olin-Aero/iarc-2017#4]
When the roombas exit the simulator beneath the 0 axes, an error is thrown and the simulator crashes. Create an out-of-bounds area that when the robots hit this area, they stop, and thus don't throw a simulator error. Also to be included should be a new map that colors this area and the in-bounds area differently.

**Comment by yycho0108** [comment]
resolved by 336a69fb9aad7ce9f0e2ea5e881e337adc9b0a1a
