### ISSUE TITLE
Develop a "strategy" structure

### ISSUE THREAD

**Issue by maxschommer** [Olin-Aero/iarc-2017#44]
Use state machine library: https://github.com/pytransitions/transitions

Create a state graph with all of our state transitions mapped out to where we just need the functions to work.

**Comment by yycho0108** [comment]
Have you considered [smach](http://wiki.ros.org/smach)?
It's a State Machine package with ROS integration.
Eric @HALtheWise and I had played with it a bit in SysRobo, and it was decent.
Sometimes it felt like it was enforcing too many restrictions, though.

Based on their README, pytransitions seem okay.
Letting you know there are alternatives, in case it doesn't work out well.
