### ISSUE TITLE
Create simple strategy to run on the drone

### ISSUE THREAD

**Issue by minhkhang1795** [Olin-Aero/iarc-2017#81]
Implement simple strategy to real drone

**Comment by HALtheWise** [comment]
Accomplished: created iarc_forebrain package to contain new, refactored strategy code

**Comment by HALtheWise** [comment]
Tasks still to be done:
- [x] Test the current hover test strategy in simulator
- [x] Make a "fly square" test strategy
- [x] Change arbiter to recalculate PID commands at high frequency
- [x] Test the fly square test strategy in hardware
- [ ] Implement strategy that follows the closest known Roomba if it knows about any Roombas
- [ ] Add push_button and redirect_roomba to Drone class
- [ ] Add subscribers for known roombas to WorldState class

**Comment by HALtheWise** [comment]
Tested and Demo'd 2/12
