### ISSUE TITLE
Y-coordinate is reversed in transforms published from 2D simulator

### ISSUE THREAD

**Issue by HALtheWise** [Olin-Aero/iarc-2017#83]
Telling the drone to go to (0,1) in the 2D simulator results in it moving right, whereas it moves left in the real world (as it should according to ROS standards). We need to figure out why this happens, and decide how to fix it.

**Comment by yycho0108** [comment]
![tf_comparison](https://user-images.githubusercontent.com/14655667/36125292-60c75242-1021-11e8-96a3-dd3dc8ef8fd9.png)

Did not observe inconsistency from 2D simulator visualization and tf frames when viewed in RViz. If there is an issue, I don't think it stems from the simulator.

**Comment by yycho0108** [comment]
Also, please post the testing configurations and procedure for reproducing the issue.

**Comment by HALtheWise** [comment]
Oops, it appears to have been working correctly. Sorry for not providing a clear repo process.
